# Generated by Django 3.2.18 on 2023-08-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230810_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pincode',
        ),
    ]
