# Generated by Django 3.2.18 on 2023-08-10 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_customer_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOGIN', 'login'), ('REFERRAL', 'referral'), ('PURCHASE', 'purchase'), ('REVIEW', 'review')], max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitory_value', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_tier', models.CharField(choices=[('BRONZE', 'bronze'), ('SILVER', 'silver'), ('GOLD', 'gold'), ('PLATINUM', 'platinum'), ('DIAMOND', 'diamond')], max_length=100)),
                ('current_points', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_points', models.PositiveIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
