# Generated by Django 3.2.18 on 2023-08-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltytoken',
            old_name='monitory_value',
            new_name='monetary_value',
        ),
    ]
