# Generated by Django 3.2.18 on 2023-08-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0002_rename_monitory_value_loyaltytoken_monetary_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BRONZE', 'bronze'), ('SILVER', 'silver'), ('GOLD', 'gold'), ('PLATINUM', 'platinum'), ('DIAMOND', 'diamond')], max_length=100)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('minimum_points', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
