# Generated by Django 3.2.18 on 2023-08-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0003_tierprogression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='loyalty_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loyalties.tierprogression'),
        ),
    ]
