# Generated by Django 3.2.18 on 2023-08-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0004_alter_loyaltyprofile_loyalty_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='current_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='maximum_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
