# Generated by Django 3.2.18 on 2023-08-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0005_auto_20230811_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='loyalty_tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loyalties.tierprogression'),
        ),
    ]
