# Generated by Django 3.2.18 on 2023-08-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyalties', '0006_alter_loyaltyprofile_loyalty_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprofile',
            name='loyalty_tier',
            field=models.ForeignKey(blank=True, default='bronze', null=True, on_delete=django.db.models.deletion.PROTECT, to='loyalties.tierprogression'),
        ),
    ]
